server:
  port: 9092
spring:
  application:
    name: serverprovider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
  instance:
    instance-id: provider9091
    prefer-ip-address: true

