server:
  port: 6060
spring:
  application:
    name: server_consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
  instance:
    instance-id: consumer6060
    prefer-ip-address: true
